spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: fanthus
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: warn
    com.fanthus: info
  file:
    path: log
    name: blog-pro.log

server:
  port: 8081